apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- manifests/persistent-volume-claim.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml

commonLabels:
  app: zai-test-service
