kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zai-test-server-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: nfs
      region: rtc
      directory: zai-test-server