apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: default
images:
- name: ZAI_TEST_SERVICE
  newName: ${imageRepository}
  newTag: '${projectVersion}'

patches:
- path: patches/ingress-host.yaml
  target:
    kind: Ingress
    name: zai-test-service
