apiVersion: apps/v1
kind: Deployment
metadata:
  name: zai-test-service
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - { key: "project", operator: In, values: [ 'zai-test-service' ] }
              topologyKey: "kubernetes.io/hostname"
